spring:
  datasource:
    url: jdbc:h2:mem:rover
    driverClassName: org.h2.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    job:
      enabled: false